# Generated by Django 5.2.6 on 2025-09-10 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustration",
            name="image_url",
            field=models.URLField(
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ]
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("story", "index")},
            },
        ),
        migrations.AddField(
            model_name="paragraph",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="stories.chapter",
            ),
        ),
    ]
