# Generated by Django 5.2.6 on 2025-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_alter_illustration_image_url_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="poster_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
