# Generated by Django 5.2.6 on 2025-09-11 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0003_story_poster_url"),
        ("stories", "000X_fix_empty_slugs"),
    ]

    operations = []
